version: "3.10"

services:
  backend:
    build:
      context: ./backend
    container_name: be_pacific-up_v1
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=hotel_cc
      - DB_USER=hotel_cc
      - DB_PASSWORD=password

  frontend:
    build:
      context: ./frontend/main
    container_name: fe_pacific-up_v2
    ports:
      - "3001:80"
    depends_on:
      - backend

  db:
    image: postgres:12-alpine
    container_name: db_pacific-up_v1
    environment:
      - POSTGRES_DB=hotel_cc
      - POSTGRES_USER=hotel_cc
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
